"""Constants for the Screensaver Overlay integration."""

DOMAIN = "screensaver_overlay"

CONF_WEATHER_ENTITY = "weather_entity"
CONF_WEATHER_ICON_SIZE = "weather_icon_size"
CONF_WEATHER_DESCRIPTION_ENTITY = "weather_description_entity"
CONF_WEATHER_DESCRIPTION_TEXT_SIZE = "weather_description_text_size"
CONF_INTERNAL_TEMPERATURE = "internal_temperature"
CONF_EXTERNAL_TEMPERATURE = "external_temperature"
CONF_RAIN_SENSOR = "rain_sensor"
CONF_CALENDARS = "calendars"
CONF_VALUE_ENTITIES = "value_entities"
CONF_STATUS_ICON_ENTITIES = "status_icon_entities"
CONF_OVERLAY_IDLE_TIMEOUT = "overlay_idle_timeout"
CONF_SCREEN_OFF_TIMEOUT = "screen_off_timeout"
CONF_MOTION_SENSOR = "motion_sensor"
CONF_SCREEN_SWITCH = "screen_switch"
CONF_BRIGHTNESS_MODE = "brightness_mode"
CONF_BRIGHTNESS_STRATEGY = "brightness_strategy"
CONF_COMPANION_NOTIFY_SERVICE = "companion_notify_service"
CONF_COMPANION_BRIGHTNESS_SENSOR = "companion_brightness_sensor"
CONF_BRIGHTNESS_REDUCTION_PERCENTAGE = "brightness_reduction_percentage"
CONF_BRIGHTNESS_LOGARITHMIC_MIN_VALUE = "brightness_logarithmic_min_value"
CONF_BRIGHTNESS_SCREEN_VALUE = "brightness_screen_value"
CONF_BRIGHTNESS_SCREENSAVER_VALUE = "brightness_screensaver_value"
CONF_RESTORE_AUTO_BRIGHTNESS = "restore_auto_brightness"
CONF_FULLY_HOST = "fully_host"
CONF_FULLY_PORT = "fully_port"
CONF_FULLY_PASSWORD = "fully_password"
CONF_FULLY_USE_HTTPS = "fully_use_https"
CONF_INFO_TEXT_SIZE = "info_text_size"
CONF_INFO_ITEMS_LIMIT = "info_items_limit"
CONF_SHOW_STATUS_ICONS = "show_status_icons"
CONF_SHOW_WEATHER_ICON = "show_weather_icon"
CONF_SHOW_CLOCK = "show_clock"
CONF_SHOW_INFO = "show_info"
CONF_SHOW_TEMPERATURES = "show_temperatures"
CONF_SHOW_HOURLY_FORECAST = "show_hourly_forecast"
CONF_LIMIT_TO_DASHBOARDS = "limit_to_dashboards"
CONF_ALLOWED_DASHBOARD_PATHS = "allowed_dashboard_paths"
CONF_BACKGROUND_IMAGES = "background_images"
CONF_BACKGROUND_CAROUSEL_INTERVAL = "background_carousel_interval"
CONF_BACKGROUND_MODE = "background_mode"

DEFAULT_OVERLAY_IDLE_TIMEOUT = 60
DEFAULT_SCREEN_OFF_TIMEOUT = 0
DEFAULT_BRIGHTNESS_MODE = "disabled"
DEFAULT_BRIGHTNESS_STRATEGY = "percentage"
DEFAULT_BRIGHTNESS_REDUCTION_PERCENTAGE = 80
DEFAULT_BRIGHTNESS_LOGARITHMIC_MIN_VALUE = 1
DEFAULT_BRIGHTNESS_SCREEN_VALUE = 180
DEFAULT_BRIGHTNESS_SCREENSAVER_VALUE = 20
DEFAULT_RESTORE_AUTO_BRIGHTNESS = False
DEFAULT_FULLY_PORT = 2323
DEFAULT_FULLY_USE_HTTPS = False
DEFAULT_FULLY_TIMEOUT = 3
DEFAULT_INFO_TEXT_SIZE = 2.0
DEFAULT_INFO_ITEMS_LIMIT = 5
DEFAULT_WEATHER_ICON_SIZE = 27
DEFAULT_WEATHER_DESCRIPTION_TEXT_SIZE = 1.8
DEFAULT_SHOW_BLOCK = True
DEFAULT_LIMIT_TO_DASHBOARDS = False
DEFAULT_BACKGROUND_CAROUSEL_INTERVAL = 60
BACKGROUND_MODE_INHERIT = "inherit"
BACKGROUND_MODE_BLACK = "black"
BACKGROUND_MODE_IMAGES = "images"
BACKGROUND_MODES = {
    BACKGROUND_MODE_INHERIT,
    BACKGROUND_MODE_BLACK,
    BACKGROUND_MODE_IMAGES,
}

BRIGHTNESS_MODE_DISABLED = "disabled"
BRIGHTNESS_MODE_COMPANION = "companion"
BRIGHTNESS_MODE_FULLY = "fully"
BRIGHTNESS_MODES = {
    BRIGHTNESS_MODE_DISABLED,
    BRIGHTNESS_MODE_COMPANION,
    BRIGHTNESS_MODE_FULLY,
}
BRIGHTNESS_STRATEGY_PERCENTAGE = "percentage"
BRIGHTNESS_STRATEGY_LOGARITHMIC = "logarithmic"
BRIGHTNESS_STRATEGY_FIXED = "fixed"
BRIGHTNESS_STRATEGIES = {
    BRIGHTNESS_STRATEGY_PERCENTAGE,
    BRIGHTNESS_STRATEGY_LOGARITHMIC,
    BRIGHTNESS_STRATEGY_FIXED,
}
BRIGHTNESS_WAKE_REAPPLY_DELAY = 1
BRIGHTNESS_WAKE_REAPPLY_INTERVAL = 2
BRIGHTNESS_WAKE_REAPPLY_MAX_ATTEMPTS = 5

FRONTEND_URL = "/screensaver_overlay/screensaver-overlay.js"
PANEL_URL = "/screensaver_overlay/screensaver-overlay-panel.js"
PANEL_PATH = "screensaver-overlay"
PANEL_ELEMENT = "screensaver-overlay-panel"
PANEL_STORAGE_KEY = f"{DOMAIN}.browser_config"
PANEL_STORAGE_VERSION = 1
STATIC_URL_PATH = "/screensaver_overlay"
SIGNAL_BROWSER_CONFIG_UPDATED = f"{DOMAIN}_browser_config_updated"
